### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by zhaowujin** [vearne/ratelimit#4]
when I run go get github.com/beefsack/go-rate, error as flow

`# github.com/vearne/ratelimit
../../go/src/github.com/vearne/ratelimit/dto.go:41:4: cannot use r.BaseRateLimiter.scriptSHA1 (type string) as type context.Context in argument to r.BaseRateLimiter.redisClient.EvalSha:
	string does not implement context.Context (missing Deadline method)
../../go/src/github.com/vearne/ratelimit/dto.go:42:11: cannot use []string literal (type []string) as type string in argument to r.BaseRateLimiter.redisClient.EvalSha
../../go/src/github.com/vearne/ratelimit/dto.go:43:6: cannot use int(r.duration / time.Microsecond) (type int) as type []string in argument to r.BaseRateLimiter.redisClient.EvalSha
../../go/src/github.com/vearne/ratelimit/dto.go:86:4: cannot use r.BaseRateLimiter.scriptSHA1 (type string) as type context.Context in argument to r.BaseRateLimiter.redisClient.EvalSha:
	string does not implement context.Context (missing Deadline method)
../../go/src/github.com/vearne/ratelimit/dto.go:87:11: cannot use []string literal (type []string) as type string in argument to r.BaseRateLimiter.redisClient.EvalSha
../../go/src/github.com/vearne/ratelimit/dto.go:88:4: cannot use r.throughputPerSec (type float64) as type []string in argument to r.BaseRateLimiter.redisClient.EvalSha
../../go/src/github.com/vearne/ratelimit/dto.go:120:4: cannot use r.BaseRateLimiter.scriptSHA1 (type string) as type context.Context in argument to r.BaseRateLimiter.redisClient.EvalSha:
	string does not implement context.Context (missing Deadline method)
../../go/src/github.com/vearne/ratelimit/dto.go:121:11: cannot use []string literal (type []string) as type string in argument to r.BaseRateLimiter.redisClient.EvalSha
../../go/src/github.com/vearne/ratelimit/dto.go:122:6: cannot use int(r.interval / time.Microsecond) (type int) as type []string in argument to r.BaseRateLimiter.redisClient.EvalSha
../../go/src/github.com/vearne/ratelimit/ratelimit.go:16:23: not enough arguments in call to client.Ping
	have ()
	want (context.Context)
../../go/src/github.com/vearne/ratelimit/ratelimit.go:16:23: too many errors`

**Comment by vearne** [comment]
╰─$ grep "beefsack/go-rate" -R ./

**Comment by vearne** [comment]
vearne/ratelimit 并不依赖 "github.com/beefsack/go-rate"
