### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by zhaowujin** [vearne/ratelimit#5]
I try TokenBucket and LeakyBucket，both are error when limiter create. I use example in https://github.com/vearne/ratelimit/blob/master/example/token_bucket_alg.go. github.com/vearne/ratelimit v0.0.5

	limiter, err := ratelimit.NewTokenBucketRateLimiter(client,
		"VideoTitleFrame", time.Minute, 200, 20, 5)

	limiter, err := ratelimit.NewLeakyBucketLimiter(client,
		"VideoTitleFrame", time.Minute, 200)

error as flow：
panic: runtime error: index out of range [0] with length 0

**Comment by vearne** [comment]
127.0.0.1:6379> type key:leaky
string
127.0.0.1:6379> type key:token
hash
127.0.0.1:6379> hgetall  key:token
1) "token_count"
2) "0"
3) "updateTime"
4) "1613805726567122"
127.0.0.1:6379> get key:leaky
"1613807035353864"

In redis, the type of redis key corresponding to TokenBucketRateLimiter and LeakyBucketLimiter are different. So the name of keys  must not be the same.
