### ISSUE TITLE
请教下：每次从redis拿回的可用操作的数量，怎么理解

### ISSUE THREAD

**Issue by cute-angelia** [vearne/ratelimit#7]
每次消费后，每次从redis拿回的可用操作的数量（可配置），这个（可用操作的数量）不应该跟消费次数一致吗？

**Comment by vearne** [comment]
比如使用的是令牌桶的话，你可以认为这个就是一次从redis拿回的令牌的数量。
为了减少对redis的压力，已经网络开销。当然最好是一次拿回多个令牌

**Comment by cute-angelia** [comment]
令牌拿回跟消费次数不一致， 这个不是影响了总的令牌发放数量了吗

**Comment by vearne** [comment]
跟消费次数是一致的，只是一次多拿几个令牌而已。比如，一次从令牌桶（redis）中拿10个令牌，那么10个令牌，在本地可以消费10次，每次消费1个。等全部消费完了，再去令牌桶（redis）中拿。

**Comment by cute-angelia** [comment]
谢谢回复

**Comment by vearne** [comment]
不客气
